version: '3'
services:
  nest-fin-app:
    container_name: nest_fin_app
    build: .
    stdin_open: true
    tty: true
    ports:
      - '3000:3000'
    environment:
      EMAIL_FROM: '${EMAIL_FROM}'
      EMAIL_APP_PASSWORD: '${EMAIL_APP_PASSWORD}'
      DATABASE_URL: 'postgresql://postgres:postgres@nest_fin_dev:5432/finance_management?schema=public&connect_timeout=300'
      REDIS_URL: 'redis://nest_fin_redis:6379'
    depends_on:
      - dev-db
      - nest-fin-redis
  dev-db:
    container_name: nest_fin_dev
    image: postgres:12
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance_management
  test-db:
    container_name: nest_fin_test
    image: postgres:12
    ports:
      - '5431:5431'
    command: -p 5431
    expose:
      - '5431'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance_management
  nest-fin-redis:
    container_name: nest_fin_redis
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - '6379:6379'
